name: Continuous Integration

on:
    push

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps: #90% dos jobs começam com um clone do código (checkout)
            - name: Checkout
              uses: actions/checkout@v5 #quando abrimos o repo conseguimos ver a versão (nesse caso é a 5)

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with: #o with sao parametros para executar o comando acima
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: givasques1101/study-apir-si:latest