name: Continuous Integration

on:
    push

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps: #90% dos jobs começam com um clone do código (checkout)
            - name: Checkout
              uses: actions/checkout@v5 #quando abrimos o repo conseguimos ver a versão (nesse caso é a 5)

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}