name: Demo de Workflow

on:
  push
  #quando demos push vai acontecer as instruções, que chamamos de jobs

  #um job é um conjunto de instruções
  #podemos dar qualquer nome a um job
  #podemos ter mais de um job 
  #a tabulação importa aqui por ser um arquivo .yaml
jobs:
  demo1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "Olá, mundo"
      - name: step2
        run: |
          echo "Mensagem 2"
          echo "Mensagem 3"
          ls -la
  demo2:
    runs-on: ubuntu-latest
    needs: demo1
    steps: 
      - name: Etapa 1
        run: echo "Estou na etapa 1"
      - name: Clone do repositorio
        uses: actions/checkout@v4
      - name: Listar pasta
        run: ls -la
